#!/usr/bin/env python3
"""Generate the 5-page front-matter print version, one per student.

Each copy carries that student's name and register number in the
Certificate "Valued by" block and in the AI Usage Declaration, the way the
department template expects. Everything else is identical to the main report.

Usage:  python3 make_front5.py   (then compile the generated .tex files)
"""
import re, subprocess, sys

SOURCE = "Orb_Project_Report.tex"
AI_PERCENT = "55"           # approximate AI usage declared on page iii

STUDENTS = [
    ("Praneeth",  "Praneeth M",     "2547142"),
    ("Parthiv",   "Parthiv Sushil", "2547141"),
    ("Hari",      "Hari Prasad",    "2547120"),
]

HEAD = """% =====================================================================
%  ORB — PROJECT REPORT: FRONT MATTER ONLY (print version)
%  Title page, Certificate, AI Usage Declaration Statement,
%  Acknowledgement, Abstract.
%  Copy for: {full} ({regno})
%  GENERATED by make_front5.py from {src} — do not edit by hand.
% =====================================================================
"""

def build(slug, full, regno):
    s = open(SOURCE, encoding="utf-8").read()
    s = s[: s.index("% ---------------- TABLE OF CONTENTS")].rstrip()
    # no table of contents in this build, so drop the TOC entries
    s = re.sub(r"\\addcontentsline\{toc\}\{chapter\}\{[^}]*\}\n?", "", s)
    # declared AI usage
    s = s.replace(r"\underline{\hspace{2.5em}}\%", r"\underline{%s}\%%" % AI_PERCENT)
    # Certificate: "Valued by" names this student
    s = s.replace(r"1. & Name \hspace{2.7cm}: Praneeth M \\[0.4cm]",
                  r"1. & Name \hspace{2.7cm}: %s \\[0.4cm]" % full)
    s = s.replace(r"2. & Register Number \hspace{0.85cm}: 2547142\\[0.4cm]",
                  r"2. & Register Number \hspace{0.85cm}: %s\\[0.4cm]" % regno)
    # AI Usage Declaration: signed by this student
    s = s.replace(r"\textbf{Name of the Students} & : & Praneeth M, Parthiv Sushil, Hari Prasad \\[0.4cm]",
                  r"\textbf{Name of the Student} & : & %s \\[0.4cm]" % full)
    s = s.replace(r"\textbf{Register Numbers} & : & 2547142, 2547141, 2547120 \\[0.4cm]",
                  r"\textbf{Register Number} & : & %s \\[0.4cm]" % regno)
    out = "Orb_Report_Front5_%s.tex" % slug
    open(out, "w", encoding="utf-8").write(
        HEAD.format(full=full, regno=regno, src=SOURCE) + s + "\n\n\\end{document}\n")
    return out

if __name__ == "__main__":
    for slug, full, regno in STUDENTS:
        tex = build(slug, full, regno)
        r = subprocess.run(["tectonic", "-X", "compile", tex],
                           capture_output=True, text=True)
        print(("ok   " if r.returncode == 0 else "FAIL ") + tex)
        if r.returncode:
            sys.stderr.write(r.stderr[-2000:]); sys.exit(1)
